
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import Header from "@/components/Header";

const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-jetbrains-mono" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} ${jetbrainsMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
